[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x4287586dde7fa5a04dd4710b76431ac23a2b96278408790a4c6f41c5a1baf897'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]